'use client'

import { AccessLog } from "@/types/database";
import { useStats, useFiles, useActivity } from "@/lib/hooks";
import { useState } from "react";
import { Sidebar } from "@/components/Sidebar";
import { Icon3D } from "@/components/Icon3D";
import { RequirePro } from "@/components/RequirePro";

interface ReportLog extends AccessLog {
    users?: { full_name: string };
    files?: { original_name: string };
}

export default function ReportsPage() {
    const { stats } = useStats();
    const { files } = useFiles();
    const { logs } = useActivity();
    const [generating, setGenerating] = useState<string | null>(null);
    const [generated, setGenerated] = useState<string | null>(null);

    const generateReport = async (reportType: string) => {
        setGenerating(reportType);

        await new Promise(r => setTimeout(r, 1500));

        let content = '';
        const now = new Date().toLocaleString();

        switch (reportType) {
            case 'security':
                content = `DATA LEASH SECURITY SUMMARY REPORT
Generated: ${now}
================================

OVERVIEW
--------
Total Protected Files: ${stats.totalFiles}
Total File Views: ${stats.totalViews}
Active Shares: ${stats.activeShares}
Threats Blocked: ${stats.threatsBlocked}

SECURITY STATUS: ${stats.threatsBlocked > 0 ? 'THREATS DETECTED' : 'ALL CLEAR'}

RECOMMENDATIONS
---------------
${stats.threatsBlocked > 0 ? '• Review blocked threats in Activity Log\n• Consider enabling auto-kill on threat detection' : '• Continue monitoring file access\n• Keep security settings enabled'}

---
Generated by Data Leash Security System
`;
                break;
            case 'access':
                content = `DATA LEASH ACCESS REPORT
Generated: ${now}
================================

RECENT FILE ACCESS LOG
----------------------
${logs.length > 0 ? logs.slice(0, 20).map((log: ReportLog) =>
                    `• ${new Date(log.timestamp).toLocaleString()} - ${log.users?.full_name || 'Unknown'} ${log.action} ${log.files?.original_name || 'file'}`
                ).join('\n') : 'No access logs recorded yet.'}

SUMMARY
-------
Total Access Events: ${logs.length}
Unique Viewers: ${new Set(logs.map((l: ReportLog) => l.user_id)).size}

---
Generated by Data Leash Access Tracking System
`;
                break;
            case 'sharing':
                content = `DATA LEASH SHARING REPORT
Generated: ${now}
================================

SHARED FILES OVERVIEW
---------------------
${files.length > 0 ? files.map(f =>
                    `• ${f.original_name}
  - Views: ${f.total_views || 0}
  - Created: ${new Date(f.created_at).toLocaleDateString()}
  - Status: Active`
                ).join('\n\n') : 'No files shared yet.'}

SUMMARY
-------
Total Files: ${files.length}
Total Views: ${stats.totalViews}

---
Generated by Data Leash Sharing System
`;
                break;
            case 'activity':
                content = `DATA LEASH ACTIVITY LOG
Generated: ${now}
================================

COMPLETE ACTIVITY HISTORY
-------------------------
${logs.length > 0 ? logs.map((log: ReportLog) =>
                    `[${new Date(log.timestamp).toLocaleString()}]
User: ${log.users?.full_name || 'Unknown'}
Action: ${log.action}
File: ${log.files?.original_name || 'N/A'}
Location: ${log.location?.city || 'Unknown'}
---`
                ).join('\n') : 'No activity recorded yet.'}

---
Generated by Data Leash Activity System
`;
                break;
        }

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `dataleash-${reportType}-report-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        setGenerating(null);
        setGenerated(reportType);
        setTimeout(() => setGenerated(null), 3000);
    };

    const reports = [
        { id: 'security', title: "Security Summary", desc: "Overview of threats and blocked actions", iconType: "shield" },
        { id: 'access', title: "Access Report", desc: "Who viewed your files and when", iconType: "eye" },
        { id: 'sharing', title: "Sharing Report", desc: "List of all shared files and recipients", iconType: "link" },
        { id: 'activity', title: "Activity Log", desc: "Complete history of all file actions", iconType: "activity" },
    ];

    return (
        <RequirePro feature="Reports">
            <div className="gradient-bg min-h-screen">
                <Sidebar />

                <main className="ml-72 p-8">
                    <div className="flex items-center gap-4 mb-2">
                        <Icon3D type="report" size="lg" />
                        <h1 className="text-3xl font-bold">Reports</h1>
                    </div>
                    <p className="text-[var(--foreground-muted)] mb-8">Download detailed reports about your file protection</p>

                    <div className="grid grid-cols-2 gap-6">
                        {reports.map((report) => (
                            <div key={report.id} className="glass-card p-6 hover:border-[var(--primary)] transition">
                                <div className="mb-4">
                                    <Icon3D type={report.iconType} size="lg" />
                                </div>
                                <h3 className="text-xl font-bold mb-2">{report.title}</h3>
                                <p className="text-sm text-[var(--foreground-muted)] mb-4">{report.desc}</p>
                                <button
                                    onClick={() => generateReport(report.id)}
                                    disabled={generating === report.id}
                                    className={`px-4 py-2 rounded text-sm font-semibold transition flex items-center gap-2 ${generated === report.id
                                        ? 'bg-[var(--success)] text-white'
                                        : 'glow-button text-black'
                                        } disabled:opacity-50`}
                                >
                                    {generating === report.id ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
                                            Generating...
                                        </>
                                    ) : generated === report.id ? (
                                        'Downloaded!'
                                    ) : (
                                        'Download Report'
                                    )}
                                </button>
                            </div>
                        ))}
                    </div>
                </main>
            </div>
        </RequirePro>
    );
}
